import { useMemo, useState } from "react";
import { BarChart3, Boxes, Cpu, Database, Download, FileText, FolderOpen, Play, Settings2, ShieldCheck, Sparkles, Zap } from "lucide-react";
import "./admin.css";
import "./interaction.css";
import "./dashboard-pages.css";
import "./config-panel.css";

const API = import.meta.env.VITE_API_URL ?? "";
type Row = Record<string, unknown>;
type Catalog = { model:string; parent:string|null; description:string; n_features:number; added_features:string[] };
type Run = { cached:boolean; run_dir:string; metrics:Row[]; importance:Row[]; fold_metrics:Row[]; domain_coverage:Row[]; missingness:Row[]; target_distribution:Row[]; cluster_sizes:Row[]; cluster_profile:Row[]; metadata:Record<string,unknown>; model_catalog:Catalog[] };
type Page = "models" | "features" | "quality" | "clusters" | "run";

export default function AdminApp() {
  const [mode,setMode]=useState("quick"), [backend,setBackend]=useState("catboost");
  const [dataPath,setDataPath]=useState("data_extracted/model_df_extracted.parquet"), [outputDir,setOutputDir]=useState("artifacts/dc5_customer_analysis");
  const [run,setRun]=useState<Run|null>(null), [busy,setBusy]=useState(false), [error,setError]=useState(""), [page,setPage]=useState<Page>("models");
  async function execute(){setBusy(true);setError("");try{const response=await fetch(`${API}/api/admin/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,backend,data_path:dataPath,output_dir:outputDir,include_city:true,clustering_enabled:mode==="full",force:false})});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Pipeline không chạy được");setRun(body);setPage("models")}catch(e){setError(e instanceof Error?e.message:"Không thể kết nối API")}finally{setBusy(false)}}
  return <div className="admin-shell"><header className="topbar"><div className="brand"><div className="brand-mark">D5</div><div><strong>DC5</strong><span>Admin / Research</span></div></div><div className="secure"><ShieldCheck size={16}/> Internal workspace</div></header><main><section className="admin-heading"><div><p className="eyebrow"><BarChart3 size={15}/> Research console</p><h1>Pipeline dashboard</h1><p className="lede">Mỗi trang tập trung vào một góc nhìn; bấm vào biểu đồ hoặc dòng dữ liệu để xem insight.</p></div><a className="button secondary" href="/">Customer UI</a></section>{error&&<div className="alert">{error}</div>}<section className="admin-grid"><Config mode={mode} backend={backend} dataPath={dataPath} outputDir={outputDir} busy={busy} setMode={setMode} setBackend={setBackend} setDataPath={setDataPath} setOutputDir={setOutputDir} execute={execute}/><section className="panel results-panel"><PageTabs page={page} setPage={setPage} hasClusters={Boolean(run?.cluster_sizes.length)}/>{!run?<Empty/>:<>{page==="models"&&<ModelsPage run={run}/>} {page==="features"&&<FeaturesPage run={run}/>} {page==="quality"&&<QualityPage run={run}/>} {page==="clusters"&&<ClustersPage run={run}/>} {page==="run"&&<RunPage run={run} outputDir={outputDir}/>}</>}</section></section></main><footer>DC5 Admin / Research <span>•</span> Internal use only</footer></div>;
}

function Config(p:{mode:string;backend:string;dataPath:string;outputDir:string;busy:boolean;setMode:(v:string)=>void;setBackend:(v:string)=>void;setDataPath:(v:string)=>void;setOutputDir:(v:string)=>void;execute:()=>void}){const modeHelp=p.mode==="quick"?"M0, M1, M4 · tối đa 3 folds":p.mode==="full"?"M0–M4 · 5 folds · clustering":"Đọc artifact mới nhất · không training";return <aside className="panel config-panel"><div className="config-title"><div className="config-icon"><Settings2 size={19}/></div><div><p className="eyebrow">Workspace setup</p><h2>Pipeline controls</h2></div></div><div className="config-section"><span className="config-section-label">Nguồn dữ liệu</span><div className="source-summary"><div><span className="source-icon"><FolderOpen size={15}/></span><span><small>Dataset</small><b title={p.dataPath}>{shortPath(p.dataPath)}</b></span></div><div><span className="source-icon"><Database size={15}/></span><span><small>Output</small><b title={p.outputDir}>{shortPath(p.outputDir)}</b></span></div></div><details className="path-settings"><summary>Thiết lập đường dẫn</summary><label><span>Đường dẫn dataset</span><input value={p.dataPath} onChange={e=>p.setDataPath(e.target.value)} aria-label="Prepared dataset path"/></label><label><span>Thư mục kết quả</span><input value={p.outputDir} onChange={e=>p.setOutputDir(e.target.value)} aria-label="Artifact directory"/></label></details></div><div className="config-section"><span className="config-section-label">Run mode</span><div className="mode-switch" role="group" aria-label="Pipeline mode">{[["quick","Quick"],["full","Full"],["report-only","Report"]].map(([value,label])=><button key={value} type="button" className={p.mode===value?"active":""} onClick={()=>p.setMode(value)}>{label}</button>)}</div><p className="mode-help"><Zap size={13}/>{modeHelp}</p></div><div className="config-section"><span className="config-section-label">Model engine</span><div className="backend-options"><button type="button" className={p.backend==="catboost"?"active":""} onClick={()=>p.setBackend("catboost")}><Cpu size={15}/><span><b>CatBoost</b><small>Tree-based</small></span></button><button type="button" className={p.backend==="logistic"?"active":""} onClick={()=>p.setBackend("logistic")}><BarChart3 size={15}/><span><b>Logistic</b><small>Baseline</small></span></button></div></div><button className="run-button" onClick={p.execute} disabled={p.busy}><span className="run-icon"><Play size={16}/></span><span><b>{p.busy?"Đang xử lý...":p.mode==="report-only"?"Mở report gần nhất":"Bắt đầu chạy pipeline"}</b><small>{p.mode==="report-only"?"Không huấn luyện lại":"Dùng cấu hình phía trên"}</small></span></button><p className="security-note"><ShieldCheck size={15}/> Internal only · không chia sẻ cho người dùng cuối</p></aside>}
function PageTabs({page,setPage,hasClusters}:{page:Page;setPage:(p:Page)=>void;hasClusters:boolean}){const tabs:[Page,string,React.ReactNode][]=[["models","Models",<BarChart3 size={15}/>],["features","Features",<Sparkles size={15}/>],["quality","Data quality",<Database size={15}/>],["clusters","Clusters",<Boxes size={15}/>],["run","Run details",<FileText size={15}/>]];return <nav className="page-tabs" aria-label="Dashboard pages">{tabs.map(([id,label,icon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)} disabled={id==="clusters"&&!hasClusters}>{icon}{label}</button>)}</nav>}
function Empty(){return <div className="empty"><BarChart3 size={28}/><h3>Chưa có kết quả trong phiên này</h3><p>Chạy pipeline hoặc chọn Report-only để mở artifact gần nhất.</p></div>}

function ModelsPage({run}:{run:Run}){const [selected,setSelected]=useState<Row>(run.metrics[0]??{});const pairs=useMemo(()=>buildDeltas(run.metrics),[run.metrics]);const spec=run.model_catalog.find(x=>x.model===String(selected.model));const parent=spec?.parent?run.metrics.find(x=>String(x.setting)===String(selected.setting)&&String(x.model)===spec.parent):undefined;const rocDelta=parent?num(selected.roc_auc)-num(parent.roc_auc):null;const prDelta=parent?num(selected.pr_auc)-num(parent.pr_auc):null;return <div className="dashboard-page"><Heading eyebrow="Trang 1" title="Kết quả mô hình" text="M0 là baseline; M1–M4 thử thêm từng nhóm feature và so sánh trên cùng validation."/><section className="model-ladder"><h3>M0–M4 khác nhau ở đâu?</h3>{run.model_catalog.map(item=><button key={item.model} className={String(selected.model)===item.model?"selected":""} onClick={()=>setSelected(run.metrics.find(x=>String(x.setting)===String(selected.setting)&&String(x.model)===item.model)??selected)}><strong>{item.model}</strong><span>{item.description}</span><small>{item.parent?`+${effectiveAdded(item,selected).length} feature so với ${item.parent}`:`${effectiveAdded(item,selected).length} feature baseline`}</small></button>)}</section><div className="metric-table"><div className="metric-row header"><span>Setting / model</span><span>ROC-AUC</span><span>PR-AUC</span></div>{run.metrics.map((m,i)=><button key={i} className={`metric-row metric-button ${selected===m?"selected":""}`} onClick={()=>setSelected(m)}><strong>{label(m)}</strong><span>{fmt(m.roc_auc)}</span><span>{fmt(m.pr_auc)}</span></button>)}</div><h3 className="subheading">ROC-AUC — bấm vào cột để phân tích</h3><div className="model-chart">{run.metrics.map((m,i)=><button key={i} className={`chart-bar ${selected===m?"selected":""}`} onClick={()=>setSelected(m)}><span>{label(m)}</span><i style={{height:`${Math.max(8,num(m.roc_auc)*100)}%`}}/><strong>{fmt(m.roc_auc)}</strong></button>)}</div><Insight title={`Insight: ${label(selected)}`}><p>{spec?.description} Model dùng <b>{String(selected.n_features??spec?.n_features??"—")} features</b>.</p>{parent?<p>So với <b>{spec?.parent}</b> trong cùng setting: ROC-AUC {changeText(rocDelta)} và PR-AUC {changeText(prDelta)}.</p>:<p>Đây là baseline để đo phần thay đổi của các model tiếp theo.</p>}<details><summary>Feature được thêm</summary><code>{spec?effectiveAdded(spec,selected).join(", "):"Baseline"}</code></details></Insight><h3 className="subheading">City ablation</h3><div className="delta-grid">{pairs.map(p=><div key={p.model}><strong>{p.model}</strong><span>Δ ROC {signed(p.roc)}</span><span>Δ PR {signed(p.pr)}</span></div>)}</div></div>}

function FeaturesPage({run}:{run:Run}){const options=useMemo(()=>Array.from(new Set(run.importance.map(x=>label(x)))),[run.importance]);const [group,setGroup]=useState(options[0]??"");const rows=run.importance.filter(x=>label(x)===group).slice(0,20);const [selected,setSelected]=useState<Row>(rows[0]??{});return <div className="dashboard-page"><Heading eyebrow="Trang 2" title="Feature importance" text="Chọn model, sau đó bấm feature để xem cách diễn giải an toàn."/><label className="field compact"><span>Setting / model</span><select value={group} onChange={e=>{setGroup(e.target.value);setSelected(run.importance.find(x=>label(x)===e.target.value)??{})}}>{options.map(x=><option key={x}>{x}</option>)}</select></label><div className="feature-bars">{rows.map((r,i)=><button key={i} onClick={()=>setSelected(r)} className={selected===r?"selected":""}><span>{String(r.feature)}</span><i><em style={{width:`${Math.min(100,num(r.importance))}%`}}/></i><strong>{fmt(r.importance)}</strong></button>)}</div><Insight title={`Insight: ${String(selected.feature??"feature")}`}><p>Importance <b>{fmt(selected.importance)}</b> trong <b>{group}</b>. Giá trị này phản ánh mức model sử dụng feature, không chứng minh quan hệ nhân quả hay hướng tác động.</p></Insight></div>}

function QualityPage({run}:{run:Run}){const all=[...run.domain_coverage.map(x=>({...x,kind:"Coverage",name:x.domain,value:x.coverage_pct})),...run.missingness.map(x=>({...x,kind:"Missingness",name:x.feature,value:x.missing_pct}))];const [selected,setSelected]=useState<Row>(all[0]??{});return <div className="dashboard-page"><Heading eyebrow="Trang 3" title="Data quality" text="Coverage, missingness và phân bố target của population hiện tại."/><div className="quality-columns"><section><h3>Domain coverage</h3>{run.domain_coverage.map((r,i)=><button key={i} onClick={()=>setSelected({...r,kind:"Coverage",name:r.domain,value:r.coverage_pct})}><span>{String(r.domain)}</span><b>{fmt(r.coverage_pct)}%</b></button>)}</section><section><h3>Top missingness</h3>{run.missingness.slice(0,12).map((r,i)=><button key={i} onClick={()=>setSelected({...r,kind:"Missingness",name:r.feature,value:r.missing_pct})}><span>{String(r.feature)}</span><b>{fmt(r.missing_pct)}%</b></button>)}</section></div><div className="target-strip">{run.target_distribution.map((r,i)=><div key={i} style={{width:`${num(r.share_pct)}%`}}><span>Target {String(r.target)}: {fmt(r.share_pct)}%</span></div>)}</div><Insight title={`${String(selected.kind??"Data")}: ${String(selected.name??"—")}`}><p>Giá trị hiện tại là <b>{fmt(selected.value)}%</b>. {selected.kind==="Missingness"?"Missing không đồng nghĩa với zero; cần kiểm tra policy trước khi impute.":"Coverage mô tả tỷ lệ xuất hiện của domain, không tự chứng minh chất lượng dự báo."}</p></Insight></div>}

function ClustersPage({run}:{run:Run}){const [selected,setSelected]=useState<Row>(run.cluster_sizes[0]??{});const profile=run.cluster_profile.find(x=>String(x.cluster)===String(selected.cluster));const top=profile?Object.entries(profile).filter(([k])=>k!=="cluster").sort((a,b)=>num(b[1])-num(a[1])).slice(0,5):[];return <div className="dashboard-page"><Heading eyebrow="Trang 4" title="Exploratory clusters" text="Bấm một cluster để xem quy mô và các profile value nổi bật."/>{run.cluster_sizes.length===0?<div className="empty"><Boxes/><h3>Chưa có clustering artifact</h3><p>Chạy Full mode và bật clustering để tạo trang này.</p></div>:<><div className="cluster-grid">{run.cluster_sizes.map((r,i)=><button key={i} onClick={()=>setSelected(r)} className={selected===r?"selected":""}><span>Cluster {String(r.cluster)}</span><strong>{Number(r.count).toLocaleString()}</strong><small>{fmt(r.share_pct)}% population</small></button>)}</div><Insight title={`Insight: Cluster ${String(selected.cluster)}`}><p>Cluster chiếm <b>{fmt(selected.share_pct)}%</b> complete cases. Các profile value cao nhất: {top.map(([k,v])=>`${k} (${fmt(v)})`).join(", ") || "chưa có"}.</p><p>Cluster là exploratory segmentation, không phải nhóm rủi ro tín dụng.</p></Insight></>}</div>}

function RunPage({run,outputDir}:{run:Run;outputDir:string}){return <div className="dashboard-page"><Heading eyebrow="Trang 5" title="Run details" text="Metadata, cấu hình tái lập và artifact của lần chạy."/><dl className="run-details"><dt>Run directory</dt><dd>{run.run_dir}</dd><dt>Cache</dt><dd>{run.cached?"Có":"Không"}</dd><dt>Pipeline version</dt><dd>{String(run.metadata.pipeline_version??"—")}</dd><dt>Run ID</dt><dd>{String(run.metadata.run_id??"—")}</dd></dl><a className="button secondary" href={`${API}/api/admin/report?output_dir=${encodeURIComponent(outputDir)}`}><Download size={16}/> Tải report HTML</a><details><summary>Metadata JSON</summary><pre>{JSON.stringify(run.metadata,null,2)}</pre></details></div>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{text}</p></div>}
function Insight({title,children}:{title:string;children:React.ReactNode}){return <aside className="insight-panel" aria-live="polite"><p className="eyebrow">Click insight</p><h3>{title}</h3>{children}<small>Mô tả dựa trên artifact hiện tại; cần review trước khi dùng cho quyết định.</small></aside>}
function label(r:Row){return `${String(r.setting??"—")} / ${String(r.model??"—")}`};function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0};function fmt(v:unknown){const n=Number(v);return Number.isFinite(n)?n.toFixed(3):"—"};function signed(v:number){return `${v>=0?"+":""}${v.toFixed(3)}`};
function changeText(value:number|null){if(value===null)return "chưa có baseline";const magnitude=Math.abs(value).toFixed(3);return value>0?`tăng ${magnitude}`:value<0?`giảm ${magnitude}`:"không đổi ở độ chính xác 3 chữ số"}
function effectiveAdded(spec:Catalog,metric:Row){return String(metric.setting).toLowerCase().includes("without city")?spec.added_features.filter(x=>x!=="city"):spec.added_features}
function shortPath(path:string){const parts=path.replaceAll("\\","/").split("/").filter(Boolean);return parts[parts.length-1]||path}
function buildDeltas(rows:Row[]){const models=Array.from(new Set(rows.map(r=>String(r.model))));return models.flatMap(model=>{const yes=rows.find(r=>String(r.model)===model&&String(r.setting).toLowerCase().includes("with city"));const no=rows.find(r=>String(r.model)===model&&String(r.setting).toLowerCase().includes("without city"));return yes&&no?[{model,roc:num(yes.roc_auc)-num(no.roc_auc),pr:num(yes.pr_auc)-num(no.pr_auc)}]:[]})}

